[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Macchiato Sapphire"
source = "community"
mode    = "dark"
 
[bar.default]
start  = [ "launcher", "clock", "gap", "cpu", "ram", "gap", "active_window", "media" ]
center = [ "workspaces" ]
end    = [ "tray", "notifications", "clipboard", "gap", "battery", "volume", "brightness", "gap", "control-center" ]
margin_ends = 8
widget_spacing = 6
 
[widget.gap]
type        = "spacer"
interactive = false

[shell]
avatar_path       = "/home/andrewvious/Pictures/berserk-pfp.jpg"
clipboard_enabled = true
show_location = false
password_style = "random"
center_password_text = true

[shell.launcher]
pinned        = [ "brave-browser", "kitty" ]
sort_by_usage = true
categories    = true
app_grid      = false

[shell.panel]
control_center_placement       = "attached"
control_center_position        = "auto"
clipboard_placement            = "attached"
clipboard_position             = "auto"
session_placement              = "attached"
session_position               = "auto"
wallpaper_placement            = "attached"
wallpaper_position             = "auto"
launcher_placement             = "floating"
launcher_position              = "center"
open_near_click_clipboard      = true
open_near_click_control_center = true
open_near_click_session        = true
open_near_click_wallpaper      = true 

[lockscreen]
blur_intensity = 0.05
tint_intensity = 0.05

[location]
address     = "Houston, TX"
auto_locate = false
 
[weather]
enabled = true
unit    = "imperial"

[wallpaper]
directory = "/home/andrewvious/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/andrewvious/Pictures/Wallpapers/wallhaven_wqv8k7.jpg"

    [wallpaper.last]
    path = "/home/andrewvious/Pictures/Wallpapers/wallhaven_wqv8k7.jpg"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 352.0
    box_width = 384.0
    cx = 1724.0
    cy = 904.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bloom_intensity = 0.45000000000000001
        inner_diameter = 0.60000000000000009
        primary_color = "on_primary"
        ring_opacity = 0.70000000000000007
        rotation_speed = 0.40000000000000002
        secondary_color = "secondary"
        sensitivity = 1.3999999999999999
        visualization_mode = "wave_rings"
        wave_thickness = 0.69999999999999996
